### ISSUE TITLE
Cant create port-channel

### ISSUE THREAD

**Issue by EvgeniyV** [jedelman8/pycsco#25]
Hi,

I am trying to create portchannel 

```
      - name: Ensure port-channel is created, add two members, and set to mode on
        nxos_portchannel: host={{ inventory_hostname }} 
                          group={{ portchannel.group }}
                          members=['Eth1/26','Eth1/27']
                          mode={{ portchannel.mode }}
                          state=present
```

but get exception on checking feature `lacp` is on:

```
Traceback (most recent call last):
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451391448.41-55211464101838/nxos_portchannel", line 1855, in <module>
    main()
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451391448.41-55211464101838/nxos_portchannel", line 171, in main
    if not nxapi_lib.feature_enabled(device, 'lacp'):
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 1951, in feature_enabled
    data = device.show(command)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/device.py", line 108, in show
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature Name          Instance  State   
--------------------  --------  --------
Flexlink              1         disabled
amt                   1         disabled
bfd                   1         disabled
bfd_app               1         disabled
bgp                   1         disabled
...
lacp                  1         enabled 
...
vtp                   1         enabled 
wccp                  1         disabled. Structured output unsupported


FATAL: all hosts have already failed -- aborting
```

in Sandbox i see this:

```
<?xml version="1.0"?>
<ins_api>
  <type>cli_show</type>
  <version>1.2</version>
  <sid>eoc</sid>
  <outputs>
    <output>
      <clierror>Feature Name          Instance  State   
--------------------  --------  --------
Flexlink              1         disabled
amt                   1         disabled
bfd                   1         disabled
...
lacp                  1         enabled 
...
</clierror>
      <input>show feature</input>
      <msg>Structured output unsupported</msg>
      <code>501</code>
    </output>
  </outputs>
</ins_api>
```

This is a fragment code in nx_api.py lines 1950 -1976:

```
  try:
        data = device.show(command)
        data_dict = xmltodict.parse(data[1])
        table = data_dict['ins_api']['outputs']['output']
        error = table.get('clierror', None)
        ...
    except (KeyError, AttributeError):
        return check
```

Nexus version 7.2(1)N1(1)

So  on the line 1951 calling `data = device.show(command)` raise an exception `clierror` - 
 which isnt catching at all

**Comment by jedelman8** [comment]
What hardware platform is this on? Please get in the habit of providing HW & SW you are using.

BTW, if you are seeing issues with the Ansible modules, please open the github issues on the nxos-ansible project.

**Comment by EvgeniyV** [comment]
moved to https://github.com/jedelman8/nxos-ansible/issues/18
