### ISSUE TITLE
pycsco compatibility issue with Python3

### ISSUE THREAD

**Issue by Guru67724** [jedelman8/pycsco#44]
# pip3 install pycsco
Collecting pycsco
  Using cached pycsco-0.3.5.tar.gz (54 kB)
Collecting xmltodict>=0.9.2
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting gtextfsm==0.2.1
  Using cached gtextfsm-0.2.1.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: py3venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-erxq7jps/gtextfsm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-erxq7jps/gtextfsm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qh7831ka
         cwd: /tmp/pip-install-erxq7jps/gtextfsm/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-erxq7jps/gtextfsm/setup.py", line 19, in <module>
        import textfsm
      File "/tmp/pip-install-erxq7jps/gtextfsm/textfsm/__init__.py", line 2, in <module>
        __version__ = textfsm.__version__
    NameError: name 'textfsm' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Guru67724** [comment]
Even textfsm installation also not solving the issue. Kindly let us know

**Comment by srbharadwaj** [comment]
can you check this out? https://github.com/Cisco-SAN/mdssdk
